[features]
seeds = false
skip-lint = false
[programs.devnet]
implementation = "A8aZpHiJhbHawHQ6g4mhaxPTXBGoc5bQecaRkro2hyGe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/masterzorgon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"