[features]
seeds = false
skip-lint = false
[programs.localnet]
chat_app = "8PKu3LwmnEvEesuMDee31MAanxrAsxAVS7eCMaku9sar"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/masterzorgon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
