[features]
seeds = false
skip-lint = false
[programs.localnet]
puppet = "9FVUQrDyzUJwR6VeaFAiQegTizfAnvbbsfX9yTTpZrWn"
proxy_program = "fcB1A9en1FaChCDrUY41nNkp8c7KWTCjkRGVYgS6SCV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/masterzorgon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
